id = "blade"
name = "Laravel Blade"
description = "Syntax Highlighting for Laravel Blade"
version = "0.0.1"
schema_version = 1
authors = ["Bruno Bernard <contact.brunobernard@gmail.com>"]
repository = "https://github.com/eznix86/blade.zed"

[grammars.blade]
repository = "https://github.com/EmranMR/tree-sitter-blade"
commit = "1c0c868b869acffb9a72f98ac677b8d0b8182605"
